version: "3.5"

services:
  openvpn:
    container_name: openvpn
    image: kkpkishan/emcpl-vpn:server
    privileged: true
    ports: 
      - "1194:1194/udp"
    environment:
      TRUST_SUB: ${TRUST_SUB}
      GUEST_SUB: ${GUEST_SUB}
      HOME_SUB: ${HOME_SUB}
    volumes:
      - ./pki:/etc/openvpn/pki
      - ./clients:/etc/openvpn/clients
      - ./config:/etc/openvpn/config
      - ./staticclients:/etc/openvpn/staticclients
      - ./log:/var/log/openvpn
      - ./fw-rules.sh:/opt/app/fw-rules.sh
      - ./checkpsw.sh:/opt/app/checkpsw.sh
      - ./server.conf:/etc/openvpn/server.conf
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - "openvpn-ui"

  openvpn-ui:
    container_name: openvpn-ui
    image: kkpkishan/emcpl-vpn:latest
    environment:
      OPENVPN_ADMIN_USERNAME: ${OPENVPN_ADMIN_USERNAME}
      OPENVPN_ADMIN_PASSWORD: ${OPENVPN_ADMIN_PASSWORD}
    privileged: true
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./:/etc/openvpn
      - ./db:/opt/openvpn-ui/db
      - ./pki:/usr/share/easy-rsa/pki
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
